---
- name: create tenant
  hosts: localhost
  gather_facts: no
  vars:
    # default op code is create
    op: "create"
    # Glance image name for images. It shoudl exist before this is executed.
    image: "ubuntu"
    # flavor should exist before this is executed
    flavor: "small"
    # creating 2 kernel VMs and 2 SRIOV VMs
    count: 2
    # list of physical routers to extend LR to
    phys_routers:
      - DC1_LEAF-1
      - DC1_LEAF-2
      - DC1_BORDER_LEAF-1
      - DC1_BORDER_LEAF-2
      - DC1_LEAF-3
      - DC1_GW-2
      - DC1_GW-1
    lrs:
        # this will be created as "normal LR", which means that it will not enable inter-tenant prefix sharing
      - lr1
        # this will be created as "external LR", which means that it will enable inter-tenant prefix sharing due to matching RTs
      - lr2_ext
    # all forementioned objects will be created in each of those tenants
    tenants:
      - tenant1
      - tenant2
  tasks:
    # physical routes where LR is going to be extended should be passed to the api in proper format, hence creating a list of formatted physical routers here
    - name: format phys routers
      set_fact:
        phys_routers_formatted: "{{ phys_routers_formatted | default([]) + ['default-global-system-config' + ':' + item] }}"
      with_items: "{{ phys_routers }}"

      # stargin a task in a loop that will create/destroy tenants depending on the operation passed in op variable
    - name: create tenants with all objects
      include_tasks: "tenant_{{ op }}.yaml"
      loop: "{{ tenants }}"
      loop_control:
        loop_var: proj_name
